import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { downloadPayslipPdf, type Payslip } from "../api/hooks";

function formatAmount(cents: number, currency: string): string {
  const major = cents / 100;
  return `${major.toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })} ${currency}`;
}

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

function formatMonth(month: string): string {
  const [yStr, mStr] = month.split("-");
  const y = Number(yStr);
  const m = Number(mStr);
  if (!Number.isFinite(y) || !Number.isFinite(m) || m < 1 || m > 12) return month;
  return `${MONTH_NAMES[m - 1]} ${y}`;
}

interface Props {
  payslips: Payslip[];
  showOwner?: boolean;
  emptyState?: ReactNode;
}

export function PayslipsTable({ payslips, showOwner = false, emptyState }: Props) {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  if (payslips.length === 0) {
    return (
      <div className="rounded-md border border-dashed border-border px-4 py-12 text-center text-sm text-muted-foreground">
        {emptyState ?? "No payslips to show."}
      </div>
    );
  }

  async function onDownload(p: Payslip) {
    setError(null);
    setDownloadingId(p.id);
    try {
      await downloadPayslipPdf(p.id, `payslip-${p.month}.pdf`);
    } catch (err) {
      setError((err as Error).message ?? "Failed to download PDF");
    } finally {
      setDownloadingId(null);
    }
  }

  return (
    <div className="space-y-2">
      {error && (
        <div role="alert" className="text-sm text-destructive">
          {error}
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border text-left text-muted-foreground">
              <th className="py-2 pr-3">Period</th>
              {showOwner && <th className="py-2 pr-3">Employee</th>}
              <th className="py-2 pr-3 text-right">Gross</th>
              <th className="py-2 pr-3 text-right">Net</th>
              <th className="py-2 pr-3">Generated by</th>
              <th className="py-2 pr-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {payslips.map((p) => (
              <tr key={p.id} className="border-b border-border/50">
                <td className="py-2 pr-3 whitespace-nowrap">{formatMonth(p.month)}</td>
                {showOwner && (
                  <td className="py-2 pr-3 whitespace-nowrap">{p.userName ?? "—"}</td>
                )}
                <td className="py-2 pr-3 text-right whitespace-nowrap">
                  {formatAmount(p.gross, p.currency)}
                </td>
                <td className="py-2 pr-3 text-right whitespace-nowrap font-medium">
                  {formatAmount(p.netAmount, p.currency)}
                </td>
                <td className="py-2 pr-3 whitespace-nowrap text-muted-foreground">
                  {p.generatedByName ?? "—"}
                </td>
                <td className="py-2 pr-3 text-right">
                  <Button
                    size="sm"
                    variant="outline"
                    disabled={downloadingId === p.id}
                    onClick={() => onDownload(p)}
                  >
                    {downloadingId === p.id ? "Downloading..." : "Download PDF"}
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
