import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Pagination } from "@/components/common/Pagination";
import { usePagination } from "@/hooks/usePagination";
import { downloadPayslipPdf, type Payslip } from "../api/hooks";

function formatAmount(cents: number, currency: string): string {
  const major = cents / 100;
  // Payroll on this platform is INR-only; force the Indian locale so the
  // grouping (lakh/crore) matches every other currency display in the app.
  // Non-INR rows would render with their currency code suffixed but the
  // numeric grouping still en-IN — acceptable until multi-currency payroll
  // ships.
  return `${major.toLocaleString("en-IN", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })} ${currency}`;
}

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

function formatMonth(month: string): string {
  const [yStr, mStr] = month.split("-");
  const y = Number(yStr);
  const m = Number(mStr);
  if (!Number.isFinite(y) || !Number.isFinite(m) || m < 1 || m > 12) return month;
  return `${MONTH_NAMES[m - 1]} ${y}`;
}

interface Props {
  payslips: Payslip[];
  showOwner?: boolean;
  emptyState?: ReactNode;
}

export function PayslipsTable({ payslips, showOwner = false, emptyState }: Props) {
  const [downloadingId, setDownloadingId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const paginated = usePagination(payslips, 10);

  if (payslips.length === 0) {
    return (
      <div className="rounded-md border border-dashed border-border px-4 py-12 text-center text-sm text-muted-foreground">
        {emptyState ?? "No payslips to show."}
      </div>
    );
  }

  async function onDownload(p: Payslip) {
    setError(null);
    setDownloadingId(p.id);
    try {
      await downloadPayslipPdf(p.id, `payslip-${p.month}.pdf`);
    } catch (err) {
      setError((err as Error).message ?? "Failed to download PDF");
    } finally {
      setDownloadingId(null);
    }
  }

  return (
    <div className="space-y-2">
      {error && (
        <div role="alert" className="text-sm text-destructive">
          {error}
        </div>
      )}
      {/* Mobile: card stack (< md) */}
      <div className="space-y-3 md:hidden">
        {paginated.items.map((p) => (
          <div
            key={p.id}
            className="rounded-md border border-border/60 bg-card/40 p-3.5 shadow-sm"
          >
            <div className="flex items-start justify-between gap-3">
              <div className="min-w-0">
                <div className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                  pay period
                </div>
                <div className="mt-0.5 text-sm font-semibold text-foreground">
                  {formatMonth(p.month)}
                </div>
                {showOwner && p.userName && (
                  <div className="mt-1 text-xs text-muted-foreground">{p.userName}</div>
                )}
              </div>
              <div className="text-right tabular-nums">
                <div className="text-base font-semibold">
                  {formatAmount(p.netAmount, p.currency)}
                </div>
                <div className="text-[11px] text-muted-foreground">
                  net · gross {formatAmount(p.gross, p.currency)}
                </div>
              </div>
            </div>
            {p.generatedByName && (
              <div className="mt-2 text-xs text-muted-foreground">
                generated by {p.generatedByName}
              </div>
            )}
            <Button
              size="sm"
              variant="outline"
              className="mt-3 w-full"
              disabled={downloadingId === p.id}
              onClick={() => onDownload(p)}
            >
              {downloadingId === p.id ? "Downloading..." : "Download PDF"}
            </Button>
          </div>
        ))}
      </div>

      {/* Desktop: table (md+) */}
      <div className="hidden overflow-x-auto md:block">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-border text-left text-muted-foreground">
              <th className="py-2 pr-3">Period</th>
              {showOwner && <th className="py-2 pr-3">Employee</th>}
              <th className="py-2 pr-3 text-right">Gross</th>
              <th className="py-2 pr-3 text-right">Net</th>
              <th className="py-2 pr-3">Generated by</th>
              <th className="py-2 pr-3 text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {paginated.items.map((p) => (
              <tr key={p.id} className="border-b border-border/50">
                <td className="py-2 pr-3 whitespace-nowrap">{formatMonth(p.month)}</td>
                {showOwner && (
                  <td className="py-2 pr-3 whitespace-nowrap">{p.userName ?? "—"}</td>
                )}
                <td className="py-2 pr-3 text-right whitespace-nowrap">
                  {formatAmount(p.gross, p.currency)}
                </td>
                <td className="py-2 pr-3 text-right whitespace-nowrap font-medium">
                  {formatAmount(p.netAmount, p.currency)}
                </td>
                <td className="py-2 pr-3 whitespace-nowrap text-muted-foreground">
                  {p.generatedByName ?? "—"}
                </td>
                <td className="py-2 pr-3 text-right">
                  <Button
                    size="sm"
                    variant="outline"
                    disabled={downloadingId === p.id}
                    onClick={() => onDownload(p)}
                  >
                    {downloadingId === p.id ? "Downloading..." : "Download PDF"}
                  </Button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <Pagination
        page={paginated.page}
        pageSize={paginated.pageSize}
        totalPages={paginated.totalPages}
        totalItems={paginated.totalItems}
        onPageChange={paginated.setPage}
        onPageSizeChange={paginated.setPageSize}
      />
    </div>
  );
}
